{
 "title": "Group C Minitwit Dashboard (WIP)",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Application status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"minitwit:5000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TOTAL HTTP RESPONSES",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "minitwit_http_responses_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Query Rate",
   "type": "timeseries",
   "description": "Queries per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(minitwit_http_responses_total[$__rate_interval])",
     "legendFormat": "Queries per second"
    }
   ]
  },
  {
   "title": "Total HTTP Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "minitwit_http_responses_total", "legendFormat": "Total Message Posts" }
   ]
  },
  {
   "title": "Response Time (P95)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "h": 8, "w": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(prometheus_http_request_duration_seconds_bucket[$__rate_interval])))\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Failures",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "h": 8, "w": 12 },
   "targets": [
    {
     "expr": "prometheus_sd_http_failures_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}