networks:
  minitwit-network:
    external: false
    name: minitwit-network

services:
  minitwit:
    image: ${DOCKER_USERNAME}/minitwitimage:latest
    container_name: minitwit-prod
    ports:
      - "80:5001" 
    environment:
      - DATABASE_URL=postgresql://minitwit_admin:12345@10.114.0.2:5432/minitwit
    networks:
      - minitwit-network
    depends_on:
      - grafana
      - prometheus
 
    restart: always

  prometheus:
    image: ${DOCKER_USERNAME}/prometheus_image:latest
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      - minitwit-network

  grafana:
    image: ${DOCKER_USERNAME}/grafana_image:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - minitwit-network
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: always
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=sesame0uvr3toi
    ports:
      - "9200:9200"
    networks:
      - minitwit-network
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.10
    container_name: logstash
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    networks:
      - minitwit-network
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.10
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ElASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=sesame0uvr3toi
    networks:
      - minitwit-network
    depends_on:
      - elasticsearch



volumes:
  grafana-storage: {}
  elasticsearch-data: {}