
version: '3.8'

services:
  minitwit:
    image: ${DOCKER_USERNAME}/minitwitimage:latest
    ports:
      - "80:5001"
    environment:
      - DATABASE_URL=postgresql://minitwit_admin:12345@10.114.0.2:5432/minitwit
    networks:
      - minitwit-network
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        order: start-first  # start new container before stopping old one
        delay: 10s
      rollback_config:
        parallelism: 1
        order: stop-first
      restart_policy:
        condition: on-failure

  prometheus:
    image: ${DOCKER_USERNAME}/prometheus_image:latest
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "127.0.0.1:9090:9090"
    networks:
      - minitwit-network
    deploy:
      placement:
        constraints:
          - node.role == manager 

  grafana:
    image: ${DOCKER_USERNAME}/grafana_image:latest
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - minitwit-network
    volumes:
      - grafana-storage:/var/lib/grafana
    deploy:
      placement:
        constraints:
          - node.role == manager

  loki:
    image: grafana/loki:3.0.0
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "127.0.0.1:3100:3100"
    networks:
      - minitwit-network
    deploy:
      placement:
        constraints:
          - node.role == manager

  promtail:
    image: grafana/promtail:3.0.0
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./promtail/config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - minitwit-network
    deploy:
      mode: global # ensures one promtail runs on all nodes in the swarm

networks:
  minitwit-network:
    driver: overlay
    attachable: true

volumes:
  grafana-storage: {}