name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    work_in_root_file_dir: true
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v6
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v4
        with:
          root_file: report/main.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v6
        with:
          name: PDF
          path: report/MSc_Group_C.pdf